### ISSUE TITLE
[Bug + Suggestion] Weird placeholders update

### ISSUE THREAD

**Issue by Apexo01** [WiIIiam278/Velocitab#57]
I would really like to use this plugin, but it's just inconvenient. Any PAPI Placeholders take a very long time to refresh, about once every 30 seconds (it's too long). Built-in placeholders work fine.

Make it possible to edit the refresh rate of a placeholders:
```yml
placeholder-refresh-intervals:
  default-refresh-interval: 500
  server:
    "%server_uptime%": 1000
    "%server_tps_1_colored%": 1000
    "%server_unique_joins%": 5000
  player:
    "%player_health%": 200
    "%player_ping%": 1000
    "%vault_prefix%": 1000
  relational:
    "%rel_factionsuuid_relation_color%": 1000
```

**Comment by WiIIiam278** [comment]
By design, PAPIProxyBridge (the library you use to do with this) caches placeholders for a certain amount of time. This is for good reason -- in cases where you have highly frequently updating animations, it'd have to network possibly thousands of plugin messages a second for players across your server `(2 + (num of players)) * num of updates per second)` -- which is far, far more data than reasonable for a TAB menu, and would affect your server's network performance.

Hence, I don't expose that option. I'm keen to have Velocitab be powerful, and I can see an argument for _maybe_ letting you modify the cache time for all placeholder messages (which you can do w/ the latest PAPIProxyBridge ver), but a level of fine control per-placeholder is just silly imo.
