### ISSUE TITLE
export display names to PlaceholderAPI

### ISSUE THREAD

**Issue by Serpentiel** [WiIIiam278/Velocitab#61]
display names for servers defined in the config aren't exported to the PlaceholderAPI, which makes it impossible to use anywhere else outside of the scoreboard itself

**Comment by WiIIiam278** [comment]
Hi there
The setting to map display names to server IDs is an internal Velocitab option; it's not meant to be exported for use in other plugins.
It's also not practical or possible to do this: PlaceholderAPI-enabled plugins _run on the backend (Spigot)_  servers; Velocitab runs on the _Velocity_ server. I offer PAPIProxyBridge to allow _Placeholders on the backend_ to be used on the frontend (Velocity) server; but this operation is only one way (since the operation to format placeholders is asynchronous and this would be too complex to implement as-is)

**Comment by Serpentiel** [comment]
ah, sorry, this definitely makes sense, I've completely forgotten that this runs on Velocity for a moment
